# Generated by Django 3.1.2 on 2020-10-22 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honeypot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('container_id', models.CharField(max_length=100)),
                ('container_ip', models.CharField(max_length=15)),
                ('container_conf', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
