# Generated by Django 3.1.2 on 2020-12-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_honeypot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('Honeypot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='api.honeypot')),
            ],
        ),
    ]
