# Generated by Django 3.1.2 on 2020-12-06 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201206_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='port',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
