# Generated by Django 3.1.2 on 2020-12-06 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trigger_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
