# Generated by Django 3.1.2 on 2020-12-06 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201206_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
