# Generated by Django 3.1.2 on 2020-12-06 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201206_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
