# Generated by Django 3.1.2 on 2020-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trigger_full_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypot',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='honeypot',
            name='container_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
