# Generated by Django 3.1.2 on 2020-12-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201207_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypot',
            name='user',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='honeypots', to=settings.AUTH_USER_MODEL),
        ),
    ]
